### ISSUE TITLE
Can not convert inline struct correctly

### ISSUE THREAD

**Issue by p1ass** [kazukousen/gouml#12]
## Issue
I would like to convert the code below.
```go
package foo

type foo struct{
	id int `json:"id"`
	bar struct{
		id int `json:"bar_id"`
	} `json:"bar"`
}
```
 
However, the output contains struct tag data.
```
package "foo" {
	class "foo" as foo.foo <<V,Orchid>> {
		-id: int
		-bar: struct{id int "json:\"bar_id\""}
	}
}
```
<img width="356" alt="スクリーンショット 2019-04-15 13 48 05" src="https://user-images.githubusercontent.com/30015728/56108144-1d65a300-5f85-11e9-80c7-01003b0f5e45.png">

I think this is because that `types.Struct` has not only field data, but also tag data like,
```
&types.Struct{
    fields:[]*types.Var{(*types.Var)(0xc0000ee3c0)},
    tags:[]string{"json:\"bar_id\""}
}
```
Therefore, when we use `types.Struct.String()`, unnecessary information is showed.

**Comment by kazukousen** [comment]
Thank you for raising the issue very much!
That's right, this issue occurred from using `types.Type.String()` .
It is temporary implementation. So I hope to use another way.

I think I would like to draw an unnamed type's field as follows:

![image](https://user-images.githubusercontent.com/13606718/56109853-4427d780-5f8d-11e9-8a5c-1c75e7c6291b.png)

**Comment by kazukousen** [comment]
nested inline struct

```go
type foo struct {
	id  int `json:"id"`
	bar struct {
		id  int `json:"bar_id"`
		baz struct {
			id int `json:"bar_baz_id"`
		}
	} `json:"bar"`
}
```

```uml
package "main" {
	class "foo" as main.foo <<V,Orchid>> {
		-id: int
		-bar: struct{id: int; baz: struct{id: int}}
	}
}
```

![image](https://user-images.githubusercontent.com/13606718/56189209-5c1d5b00-6062-11e9-81f5-fd136456f653.png)
