### ISSUE TITLE
Ignore *_test.go files

### ISSUE THREAD

**Issue by utx0** [kazukousen/gouml#40]
Just giving this tool a spin and its taking forever to parse some of my *_test.go files. Be great if these could be ignored either by a cli flag or even by default.

**Comment by kazukousen** [comment]
Thank you for the nice issue.
I think it should be ignoring `*_test.go` files by default too.

**Comment by kazukousen** [comment]
@lukekhamilton
please try `go get -u` again

**Comment by utx0** [comment]
Thanks, worked perfectly.
